services:
  stockexchangeangularui:
    image: stockexchangeangularui
    build:
      context: .
      dockerfile: StockStockExchange.AngularUI/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 443:443
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/remapping.umd.js"]
