services:
  stockexchangeangularui:
    image: stockexchangeangularui
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443
